services:
  whisper-api:
    build:
      context: ./whisper
    volumes:
      - ./audio:/audio:ro
      - ./build/whisper:/root/.cache
    environment:
      - WHISPER_MODEL=large-v3
      - WHISPER_DEVICE=cpu
      - WHISPER_COMPUTE_TYPE=int8
      - WHISPER_LANGUAGE=ko

  meeting-summary-bot:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./audio:/app/audio:rw
      - ./PROMPT:/app/PROMPT:ro
